src/Entity/Emprunt.php
<?php

namespace App\Entity;

use App\Repository\EmpruntRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmpruntRepository::class)]
class Emprunt
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private ?\DateTimeInterface $date_emprunt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_retour = null;

    #[ORM\ManyToOne(inversedBy: 'emprunts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Livre $livre = null;

    #[ORM\ManyToOne(inversedBy: 'emprunts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Emprunteur $emprunteur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEmprunt(): ?\DateTimeInterface
    {
        return $this->date_emprunt;
    }

    public function setDateEmprunt(\DateTimeInterface $date_emprunt): self
    {
        $this->date_emprunt = $date_emprunt;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }

    public function getEmprunteur(): ?Emprunteur
    {
        return $this->emprunteur;
    }

    public function setEmprunteur(?Emprunteur $emprunteur): self
    {
        $this->emprunteur = $emprunteur;

        return $this;
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 190)]
    private ?string $titre = null;

    #[ORM\Column(nullable: true)]
    private ?int $anne_edition = null;

    #[ORM\Column]
    private ?int $nombres_pages = null;

    #[ORM\Column(length: 190, nullable: true)]
    private ?string $code_isbn = null;

    #[ORM\ManyToOne(inversedBy: 'livres')]
    private ?Auteur $auteur = null;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'livres')]
    private Collection $genres;

    #[ORM\OneToMany(mappedBy: 'livre', targetEntity: Emprunt::class)]
    private Collection $emprunts;

    public function __construct()
    {
        $this->genres = new ArrayCollection();
        $this->emprunts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAnneEdition(): ?int
    {
        return $this->anne_edition;
    }

    public function setAnneEdition(?int $anne_edition): self
    {
        $this->anne_edition = $anne_edition;

        return $this;
    }

    public function getNombresPages(): ?int
    {
        return $this->nombres_pages;
    }

    public function setNombresPages(int $nombres_pages): self
    {
        $this->nombres_pages = $nombres_pages;

        return $this;
    }

    public function getCodeIsbn(): ?string
    {
        return $this->code_isbn;
    }

    public function setCodeIsbn(?string $code_isbn): self
    {
        $this->code_isbn = $code_isbn;

        return $this;
    }

    public function getAuteur(): ?Auteur
    {
        return $this->auteur;
    }

    public function setAuteur(?Auteur $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    /**
     * @return Collection<int, Emprunt>
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): self
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts[] = $emprunt;
            $emprunt->setLivre($this);
        }

        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): self
    {
        if ($this->emprunts->removeElement($emprunt)) {
            
            if ($emprunt->getLivre() === $this) {
                $emprunt->setLivre(null);
            }
        }

        return $this;
    }
}

templates/admin_book/_delete_form.html.twig
<form class='btn'method="post" action="{{ path('app_admin_book_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
    <button class="btn btn-primary">Supprimer</button>
</form>

templates/admin_book/_form.html.twig
{{form_start(form)}}
    {{form_widget(form)}}
    <button class='btn btn-primary'>{{button_label|default('Save')}}</button>
{{form_end(form)}}

templates/admin_book/book_details.html.twig
{% extends 'base.html.twig' %}
{% block title %}detail du livre{% endblock %}

{% block body %}
<a href="{{ path('app_admin_book') }}">back to list</a>
<h1>Detail de {{livre.titre}}</h1>
<ul>
<li>Titre : {{livre.titre}}</li>

{% if  livre.emprunts|length == 0 %}
<li> disponible </li>
{% endif %}
{% for emprunt in livre.emprunts %}
{% if emprunt.dateRetour == null %}
<li> indisponible </li>
{% else %}
    <li> disponible </li>

{% endif %}
{% endfor %}
<li>année d'édition : {{livre.anneeEdition}}</li>
<li>nombre de pages : {{livre.nombrePages}}</li>
<li>code ISBN: {{livre.codeIsbn}}</li>
<li>cote : {{livre.Id}}</li>

    <li>Auteur : {{auteurs.nom}} {{auteurs.prenom}}</li>

 Genre(s) :</li>
{% for genre in livre.genres %}
 <li>   {{genre.nom}}</li>
{% endfor %}
</ul>
<a href="{{path('app_admin_book_edit', {id:livre.id})}}">Editer ce livre</a>

    {{ include('admin_book/_delete_form.html.twig') }}

{% endblock %}

templates/admin_book/book_edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}modification du Livre{% endblock %}
{% block body %}
    <h1>modification du livre {{livre.id}}</h1>

    {{ include('admin_book/_form.html.twig') }}

    <a href="{{ path('app_admin_book') }}">back to list</a>


{% endblock %}

templates/admin_book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}administration des livres{% endblock %}

{% block body %}
        <a class='btn btn-primary' href="{{ path('app_admin_book_new') }}">Enregistrer un nouveau livre</a>
<ul>
{% for livre in livres %}
    <li><a href='{{path('app_admin_book_show',{"id":livre.id})}}'>{{livre.titre}}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/admin_book/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}Nouveaux livre{% endblock %}
{% block body %}
    <h1>Créé un nouveau livre</h1>

    {{ include('admin_book/_form.html.twig') }}

    <a href="{{ path('app_admin_book') }}">back to list</a>
{% endblock %}