src/Entity/Emprunt.php
<?php

namespace App\Entity;

use App\Repository\EmpruntRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmpruntRepository::class)]
class Emprunt
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private ?\DateTimeInterface $date_emprunt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_retour = null;

    #[ORM\ManyToOne(inversedBy: 'emprunts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Livre $livre = null;

    #[ORM\ManyToOne(inversedBy: 'emprunts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Emprunteur $emprunteur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEmprunt(): ?\DateTimeInterface
    {
        return $this->date_emprunt;
    }

    public function setDateEmprunt(\DateTimeInterface $date_emprunt): self
    {
        $this->date_emprunt = $date_emprunt;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }

    public function getEmprunteur(): ?Emprunteur
    {
        return $this->emprunteur;
    }

    public function setEmprunteur(?Emprunteur $emprunteur): self
    {
        $this->emprunteur = $emprunteur;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[Groups(['read', 'write'])]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[Groups(['read', 'write'])]
    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[Groups(['read', 'write'])]
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[Groups(['read'])]
    #[ORM\Column]
    private ?string $password = null;

    #[Groups(['read', 'write'])]
    #[ORM\Column(nullable: false)]
    private ?bool $enabled = null;

    #[Groups(['read', 'write'])]
    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;


    #[Groups(['read', 'write'])]
    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/AdminEmprunteurController.php
<?php

namespace App\Controller;

use App\Entity\Emprunteur;
use App\Form\EmprunteurType;
use App\Repository\EmprunteurRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


#[Route('/admin/emprunteur')]
class AdminEmprunteurController extends AbstractController
{
    #[Route('/', name: 'app_admin_emprunteur')]
    public function index(EmprunteurRepository $emprunteurRepository): Response
    {
        return $this->render('admin_emprunteur/index.html.twig', [
            'controller_name' => 'AdminEmprunteurController',
            'emprunteurs'=>$emprunteurRepository->findAll()
        ]);
    }
    #[Route('/new', name: 'app_admin_emprunteur_new', methods:['GET','POST'])]
    public function new(EmprunteurRepository $emprunteurRepository, Request $request): Response
    {
        $emprunteur=new Emprunteur();
        $form = $this->createForm(EmprunteurType::class,$emprunteur);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $emprunteur=$emprunteur->setCreatedAt(new DateTimeImmutable());
            $emprunteur=$emprunteur->setUpdatedAt(new DateTimeImmutable());
            $emprunteurRepository->add($emprunteur,true);

            return $this->redirectToRoute('app_admin_emprunteur', [], Response::HTTP_SEE_OTHER);
        };
        return $this->renderForm('admin_emprunteur/new.html.twig', [
            'form'=>$form,
            'emprunteur'=>$emprunteur
        ]);
    }
    #[Route('/{id}',name:'app_admin_emprunteur_show',methods:['GET'])]
    public function show(Emprunteur $emprunteur):Response
    {

        return $this->render('admin_emprunteur/emprunteur_details.html.twig', [
            'emprunteur'=>$emprunteur
        ]);
    }
    #[Route('/{id}/edit',name:'app_admin_emprunteur_edit',methods:['GET','POST'])]
    public function edit(Emprunteur $emprunteur,Request $request,EmprunteurRepository $emprunteurRepository):Response
    {
        $form= $this->createForm(EmprunteurType::class,$emprunteur);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $emprunteur=$emprunteur->setUpdatedAt(new DateTimeImmutable());
            $emprunteurRepository->add($emprunteur, true);
            return $this->redirectToRoute('app_admin_emprunteur', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_emprunteur/emprunteur_edit.html.twig', [
            'emprunteur'=>$emprunteur,
            'form'=>$form->createView(),
        ]);
    }
    #[Route('/{id}',name:'app_admin_emprunteur_delete',methods:['POST'])]
    public function delete(EmprunteurRepository $emprunteurRepository, Emprunteur $emprunteur,Request $request):Response
    {        
        if ($this->isCsrfTokenValid('delete'.$emprunteur->getId(), $request->request->get('_token'))) {
        $emprunteurRepository->remove($emprunteur, true);
    }


        return $this->redirectToRoute('app_admin_emprunteur', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_emprunteur/_delete_form.html.twig
<form class='btn'method="post" action="{{ path('app_admin_emprunteur_delete', {'id': emprunteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ emprunteur.id) }}">
    <button class="btn btn-primary">Supprimer</button>
</form>

templates/admin_emprunteur/_form.html.twig
{{form_start(form)}}
    {{form_widget(form)}}
    <button class='btn btn-primary'>{{button_label|default('Save')}}</button>
{{form_end(form)}}

templates/admin_emprunteur/emprunteur_details.html.twig
{% extends 'base.html.twig' %}
{% block title %}detail de l'emprunteur{% endblock %}

{% block body %}
    <a href="{{ path('app_admin_emprunteur') }}">back to list</a>
<h1>Details de l'emprunteur {{emprunteur.id}}</h1>
<ul>
<li>{{emprunteur.nom}}{{emprunteur.prenom}}</li>
<li>{{emprunteur.tel}}</li>
</ul>
{% if emprunteur.emprunts|length == 0 %}
<p>Aucun emprunt enregistré</p>
{% else %}
    <p>Liste des emprunts :</p>
<ul>
{% for emprunt in emprunteur.emprunts %}
<li>Le {{emprunt.dateEmprunt|date('d-m-Y')}}</li>
    <li>{{emprunt.livre.titre}}</li>
    {% if emprunt.dateRetour == null %}
        <li>Non rendu</li>
        {% else %}
        <li> Rendu le {{emprunt.dateRetour|date('d-m-Y')}}</li>
    {% endif %}
{% endfor %}
</ul>
{% endif %}
<ul>
<li>{{emprunteur.createdAt|date('d-m-Y')}}</li>
<li>{{emprunteur.updatedAt|date('d-m-Y')}}</li>
</ul>
<a href="{{path('app_admin_emprunteur_edit', {id:emprunteur.id})}}">Editer cet emprunt</a>

    {{ include('admin_emprunteur/_delete_form.html.twig') }}

{% endblock %}

templates/admin_emprunteur/emprunteur_edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}modification de l'emprunteur{% endblock %}
{% block body %}
    <h1>modification de l'emprunteur {{emprunteur.id}}</h1>

    {{ include('admin_emprunteur/_form.html.twig') }}

    <a href="{{ path('app_admin_emprunteur') }}">back to list</a>


{% endblock %}

templates/admin_emprunteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administration des emprunteur{% endblock %}

{% block body %}
<ul>
        <a class='btn btn-primary' href="{{ path('app_admin_emprunteur_new') }}">Enregistrer un nouvel emprunteur</a>
{% for emprunteur in emprunteurs %}
    <li><a href=" {{ path('app_admin_emprunteur_show',{"id":emprunteur.id}) }}">{{emprunteur.prenom}} {{emprunteur.nom}}</a></li>
    {% if emprunteur.actif == false %}
    <li>Innactif</li>
    {% else %}
        <li>Actif</li>
        
    {% endif %}
{% endfor %}
</ul>
{% endblock %}

templates/admin_emprunteur/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}Nouvel emprunteur{% endblock %}
{% block body %}
    <h1>Créé un nouvel emprunteur</h1>

    {{ include('admin_emprunteur/_form.html.twig') }}

    <a href="{{ path('app_admin_emprunteur') }}">back to list</a>
{% endblock %}